### ISSUE TITLE
About point cloud position retrieval

### ISSUE THREAD

**Issue by lkf263** [jac99/MinkLoc3D#10]
I appreciate your great work.
I am curious about how you achieved the visualization of point cloud position retrieval, similar to Figure 4 or5. If you could provide insights into this, I would be immensely grateful.Thank you!

**Comment by jac99** [comment]
Hi,

I've used the Jupyer notebook in the attached file to generate point cloud plots (separate plot for each point cloud - based on the kNN search results saved to a .txt file). Then, I've combined separate plots in Latex:
[point_cloud_visualiazation_code.zip](https://github.com/jac99/MinkLoc3D/files/14073895/point_cloud_visualiazation_code.zip)

\captionsetup[subfigure]{labelformat=empty}

\begin{figure*}[htbp]
\centering
\setcounter{subfigure}{0}
\subfloat[query]{%
\includegraphics[width=2.7cm,height=2cm,trim={1.5cm 1cm 0.5cm 2cm},clip,cfbox=black 0.5pt 0.5pt]{images/nn_1.png}}
\hfill
\subfloat[dist=1.13 TP]{%
\includegraphics[width=2.7cm,height=2cm,trim={1.5cm 1cm 0.5cm 2cm},clip,cfbox=mygreen 0.5pt 0.5pt]{images/nn_3.png}}
\hfill
\subfloat[dist=1.40 TP]{%
\includegraphics[width=2.7cm,height=2cm,trim={1.5cm 1cm 0.5cm 2cm},clip,cfbox=mygreen 0.5pt 0.5pt]{images/nn_5.png}}
\hfill
\subfloat[dist=1.44 TP]{%
\includegraphics[width=2.7cm,height=2cm,trim={1.5cm 1cm 0.5cm 2cm},clip,cfbox=mygreen 0.5pt 0.5pt]{images/nn_7.png}}
\hfill
\subfloat[dist=1.45 TP]{%
\includegraphics[width=2.7cm,height=2cm,trim={1.5cm 1cm 0.5cm 2cm},clip,cfbox=mygreen 0.5pt 0.5pt]{images/nn_9.png}}
\hfill
\subfloat[dist=1.82 FP]{%
\includegraphics[width=2.7cm,height=2cm,trim={1.5cm 1cm 0.5cm 2cm},clip,cfbox=red 0.5pt 0.5pt]{images/nn_11.png}}

\caption{Nearest neighbours search results in Oxford evaluation subset. The leftmost column shows a query point cloud. Other columns show its five nearest neighbours. \emph{dist} is an Euclidean distance in the descriptor space. TP indicates true positive and FP false positive.}
\label{fig:search_results}
\end{figure*}

\captionsetup[subfigure]{labelformat=parens}

**Comment by jac99** [comment]
Closing
